package dao

//import "C"
import (
	// "github.com/kennyzhu/go-os/dbservice/subscriber"

	"github.com/micro/go-micro"

	"github.com/kennyzhu/go-os/src/dbservice/conf"
	_ "github.com/kennyzhu/go-os/src/dbservice/conf"
	"github.com/kennyzhu/go-os/src/dbservice/handler"
	"github.com/kennyzhu/go-os/src/dbservice/models"
	"github.com/kennyzhu/go-os/src/log"
)

//generated by: micro new --type srv --alias dbservice github.com/kennyzhu/go-os/
func main() {
	// New Service
	service := micro.NewService(
		micro.Name(conf.AppConf.SrvName),
		micro.Version("1"),
	)

	// Initialise service
	service.Init()

	//Initialise models
	models.Init(false)

	// Register Handler,each goroutine..
	handler.Init( service.Server() )

	// Register Struct as Subscriber
	//micro.RegisterSubscriber("go.micro.srv.template", service.Server(), new(subscriber.Example))
	//micro.RegisterSubscriber("go.micro.srv.template", service.Server(), subscriber.Handler)

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
